# Generated by Django 5.0.3 on 2024-04-18 02:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(default=0)),
                ('nome_produto', models.CharField(default='sorvete', max_length=50, primary_key=True, serialize=False, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('picole', 'Picolé'), ('massa', 'Massa'), ('pote', 'Pote')], default='picole', max_length=30, verbose_name='Categoria')),
                ('subcategoria', models.CharField(choices=[('PA', 'Paleta'), ('PT', 'Picolé Tradicional'), ('PG', 'Picolé Especial'), ('PK', 'Picolé Kids'), ('M5L', 'Massa 5 Litros'), ('MA', 'Massa Açaí'), ('MT', 'Massa Tradicional'), ('ME', 'Massa Especial'), ('PMA', 'Pote Massa Açaí'), ('PMT', 'Pote Massa Tradicional'), ('PME', 'Pote Massa Especial')], default='PA', max_length=30, verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('nome_loja', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nome da Loja')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Número de telefone deve ser inserido no formato: '+999999999'. Até 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Associado')),
            ],
            options={
                'verbose_name': 'Lojista',
                'verbose_name_plural': 'Lojistas',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('quantidade', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='lojistas.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(choices=[('realizado', 'Realizado'), ('nao_realizado', 'Não Realizado'), ('em_andamento', 'Em Andamento')], default='em_andamento', help_text='Estado do processo da reserva', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True, help_text='Data e hora da realização da reserva')),
                ('lojista', models.ForeignKey(help_text='Lojista responsável pela reserva', on_delete=django.db.models.deletion.CASCADE, to='lojistas.lojista')),
            ],
        ),
    ]
